2015-04-17 18:09:58 Error: Fatal Error (4): syntax error, unexpected '$client_id' (T_VARIABLE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 115]
2015-04-17 18:09:58 Error: [FatalErrorException] syntax error, unexpected '$client_id' (T_VARIABLE), expecting function (T_FUNCTION)
Request URL: /Expence/users
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 115)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 115, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 115, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 18:11:13 Error: Fatal Error (4): syntax error, unexpected '?>', expecting function (T_FUNCTION) in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 192]
2015-04-17 18:11:13 Error: [FatalErrorException] syntax error, unexpected '?>', expecting function (T_FUNCTION)
Request URL: /Expence/users
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 192)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 192, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 192, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 18:11:37 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 86]
2015-04-17 18:11:37 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Expence/users
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 18:11:45 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 86]
2015-04-17 18:11:45 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Expence/users/login
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 18:12:11 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 86]
2015-04-17 18:12:11 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Expence/users/login
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 18:12:13 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 86]
2015-04-17 18:12:13 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Expence/users/login
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 86, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 18:19:07 Error: [MissingActionException] Action UsersController::oauthCallback() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'oauthCallback',
)
Request URL: /Expence/users/oauthCallback
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Expence\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 C:\xampp\htdocs\Expence\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-04-17 18:19:17 Error: [MissingActionException] Action UsersController::oauthCallback() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'oauthCallback',
)
Request URL: /Expence/users/oauthCallback
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Expence\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 C:\xampp\htdocs\Expence\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-04-17 18:21:58 Error: Fatal Error (4): syntax error, unexpected 'define' (T_STRING), expecting function (T_FUNCTION) in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 124]
2015-04-17 18:21:58 Error: [FatalErrorException] syntax error, unexpected 'define' (T_STRING), expecting function (T_FUNCTION)
Request URL: /Expence/users/login
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 124)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 124, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 124, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 19:04:03 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Expence\app\Controller\UsersController.php, line 148]
2015-04-17 19:04:03 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Expence/users/oauth_callback?code=4%2FwhIlC_LP9FVjZiWWIlitOWkaJQdJ4tJ_4h11YanZVRY.4keZFSmqPZ4XBrG_bnfDxpI6epyQmQI&authuser=0&num_sessions=1&hd=wasedasai.net&session_state=aa00fd50f3ea1f1e575f8198dfbc9a7ac38131e0..b1d1&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 148)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 148, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 148, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-17 19:28:12 Error: Fatal Error (4): syntax error, unexpected '$data' (T_VARIABLE) in [C:\xampp\htdocs\Expence\app\Model\User.php, line 34]
2015-04-17 19:28:12 Error: [FatalErrorException] syntax error, unexpected '$data' (T_VARIABLE)
Request URL: /Expence/users/login
Stack Trace:
#0 C:\xampp\htdocs\Expence\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 34, Array)
#2 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 34, Array)
#3 C:\xampp\htdocs\Expence\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-18 12:48:42 Error: [MissingControllerException] Controller class ExpensesController could not be found.
Exception Attributes: array (
  'class' => 'ExpensesController',
  'plugin' => NULL,
)
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-04-18 12:49:02 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 6]
2015-04-18 12:49:02 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 6)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 6, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 6, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 08:39:33 Error: Fatal Error (4): syntax error, unexpected '$' in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 12]
2015-04-21 08:39:33 Error: [FatalErrorException] syntax error, unexpected '$'
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 08:59:26 Error: Fatal Error (4): syntax error, unexpected '<<' (T_SL) in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 18]
2015-04-21 08:59:26 Error: [FatalErrorException] syntax error, unexpected '<<' (T_SL)
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 18, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 18, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 08:59:53 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 55]
2015-04-21 08:59:53 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 09:00:48 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 55]
2015-04-21 09:00:48 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 09:00:57 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 55]
2015-04-21 09:00:57 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 09:02:53 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 47]
2015-04-21 09:02:53 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 09:02:55 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 47]
2015-04-21 09:02:55 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 09:04:34 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 55]
2015-04-21 09:04:34 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 09:05:08 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 47]
2015-04-21 09:05:08 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 09:05:51 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 55]
2015-04-21 09:05:51 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 55, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 16:05:50 Error: Fatal Error (1): Call to a member function user() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 30]
2015-04-21 16:05:50 Error: [FatalErrorException] Call to a member function user() on a non-object
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 30)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 30, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 30, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 16:07:20 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 19]
2015-04-21 16:07:20 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 19, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 19, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 16:08:56 Error: Fatal Error (1): Call to a member function deny() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 19]
2015-04-21 16:08:56 Error: [FatalErrorException] Call to a member function deny() on a non-object
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 19, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 19, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-21 16:08:59 Error: Fatal Error (1): Call to a member function deny() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 19]
2015-04-21 16:08:59 Error: [FatalErrorException] Call to a member function deny() on a non-object
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 19, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 19, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 02:54:47 Error: Fatal Error (4): syntax error, unexpected '$numbers' (T_VARIABLE), expecting '(' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 37]
2015-04-23 02:54:47 Error: [FatalErrorException] syntax error, unexpected '$numbers' (T_VARIABLE), expecting '('
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 37, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 02:56:26 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'total' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(Expense), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(52): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-04-23 03:15:33 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\Controller\UsersController.php, line 29]
2015-04-23 03:15:33 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/users/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 29)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 29, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 29, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 12:52:22 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 62]
2015-04-23 12:52:22 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/expenses/view/04001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 62)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 62, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 62, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:23:09 Error: Fatal Error (4): syntax error, unexpected 'message' (T_STRING), expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 16]
2015-04-23 13:23:09 Error: [FatalErrorException] syntax error, unexpected 'message' (T_STRING), expecting ')'
Request URL: /Accounts/users/oauth_callback?code=4%2F5Q8tkHzWrvWLfBlCNBMbSBYJ7EEWPAEDNOAnn8qWpfs.ohsR9ZNsz2URBrG_bnfDxpJywgjMmQI&authuser=0&session_state=83ddd8191f7a450ba463c913034dc13cc557798c..c4a4&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 16)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 16, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 16, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:29:07 Error: Fatal Error (4): syntax error, unexpected '$domain' (T_VARIABLE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 8]
2015-04-23 13:29:07 Error: [FatalErrorException] syntax error, unexpected '$domain' (T_VARIABLE), expecting function (T_FUNCTION)
Request URL: /Accounts/users/oauth_callback?code=4%2FhmC5hGoNRxyJQL13QgiC1O4CuUZjmmN4afmvQVXxyu0.kstr2G3JGwEegrKXntQAax0CsRPMmQI&authuser=0&num_sessions=2&session_state=2eb5fd6c225bc71815849cb115c31896aef0136f..64fa&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:29:18 Error: Fatal Error (4): syntax error, unexpected '$domain' (T_VARIABLE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 8]
2015-04-23 13:29:18 Error: [FatalErrorException] syntax error, unexpected '$domain' (T_VARIABLE), expecting function (T_FUNCTION)
Request URL: /Accounts/users/oauth_callback?code=4%2FN_kstXCL_QaiC9nQWk2-Xvasup0jbJzfoCIle-sQyzk.0hpWenDoGlcZBrG_bnfDxpLiBhTMmQI&authuser=0&num_sessions=2&session_state=ec110cc3c34bac410ee8910773e2fee64615837a..98b0&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:30:00 Error: Fatal Error (4): syntax error, unexpected '.', expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 17]
2015-04-23 13:30:00 Error: [FatalErrorException] syntax error, unexpected '.', expecting ')'
Request URL: /Accounts/users/oauth_callback?code=4%2F6hWziaoWlbnpKzG_K_F5JdZVLbhXdZGU5MUxkmukvvw.4uX6oM_9Ia8RBrG_bnfDxpIgURXMmQI&authuser=0&num_sessions=2&session_state=c69ca1e93aeac68b3c4ddc4092c9825c289c9ec0..f7db&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:32:38 Error: Fatal Error (4): syntax error, unexpected '(', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 8]
2015-04-23 13:32:38 Error: [FatalErrorException] syntax error, unexpected '(', expecting ',' or ';'
Request URL: /Accounts/users/oauth_callback?code=4%2F6KuGFg_Qe2UUASvLjSxts2qlL7-ZlBsO_0XWk_4i3mU.srFpswSM2DIdBrG_bnfDxpKaIxrMmQI&authuser=0&num_sessions=2&session_state=0197e4e5cbd85675673bd24fb7b5fcfaa07ec6e0..da63&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:36:29 Error: Fatal Error (4): syntax error, unexpected '.', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 8]
2015-04-23 13:36:29 Error: [FatalErrorException] syntax error, unexpected '.', expecting ',' or ';'
Request URL: /Accounts/users/oauth_callback?code=4%2Fh7PthNUX6Dj4NpnLIrnkMXUO8xa05g6qW5jfiKuZMa4.glt2Xa4pOeobgrKXntQAax1gKiHMmQI&authuser=0&num_sessions=2&session_state=6b88216ab2bcf5639ad13d5738893462696a73b9..368b&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:40:22 Error: Fatal Error (4): syntax error, unexpected '(', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 8]
2015-04-23 13:40:22 Error: [FatalErrorException] syntax error, unexpected '(', expecting ',' or ';'
Request URL: /Accounts/users/oauth_callback?code=4%2Fi7jRLoto_J1cX591KPabKdkJU8k2C8N8vzk2wwUSCd4.sg1PehYpP5UQgrKXntQAax0QSijMmQI&authuser=0&num_sessions=2&session_state=993b190444258599173afa78395e5b0f19019397..9f6b&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:41:54 Error: Fatal Error (4): syntax error, unexpected '.', expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 17]
2015-04-23 13:41:54 Error: [FatalErrorException] syntax error, unexpected '.', expecting ')'
Request URL: /Accounts/users/login
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:42:37 Error: Fatal Error (4): syntax error, unexpected '$domain' (T_VARIABLE), expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 17]
2015-04-23 13:42:37 Error: [FatalErrorException] syntax error, unexpected '$domain' (T_VARIABLE), expecting ')'
Request URL: /Accounts/users/oauth_callback?code=4%2F207BM_SbDpG1pTN71--_L_55BIjSFcT0vLGYf-rULpA.UuSzgbFw-5QdgrKXntQAax1MbSzMmQI&authuser=0&num_sessions=2&session_state=772842e681ab1ebf2837f04175d136dfa5b396b1..7b64&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:44:43 Error: Fatal Error (4): syntax error, unexpected '|', expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 15]
2015-04-23 13:44:43 Error: [FatalErrorException] syntax error, unexpected '|', expecting ')'
Request URL: /Accounts/users/oauth_callback?code=4%2FpWWvJukKEi7wl-e4q-P45xJGr1iQzmnNkBEO2Owb1Ps.8gKoDsxFj-wegrKXntQAax0OQjDMmQI&authuser=0&num_sessions=2&session_state=b15302235a6798bd8962296a58ac1661661d214a..1669&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 15, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 15, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:45:01 Error: Fatal Error (4): syntax error, unexpected '/', expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 15]
2015-04-23 13:45:01 Error: [FatalErrorException] syntax error, unexpected '/', expecting ')'
Request URL: /Accounts/users/oauth_callback?code=4%2FHLicMe2ZIulvPbyNFRGliBEa43tAau5Ns-E6zTXbEJo.goXDUJUKrNAUgrKXntQAax3YzzDMmQI&authuser=0&num_sessions=2&session_state=78bf7e4fe17f2e342eee37856826ad905922372b..1434&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 15, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 15, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 13:56:00 Error: Fatal Error (1): Call to a member function set() on a non-object in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 44]
2015-04-23 13:56:00 Error: [FatalErrorException] Call to a member function set() on a non-object
Request URL: /Accounts/users/oauth_callback?code=4%2FL1nJhfJpAmwbVQ1ms4Yw1NU7IerbiiFPUxjJKHIV7J0.krL7rxJsnEUUgrKXntQAax2o7ETMmQI&authuser=0&num_sessions=2&session_state=1410b25e32066f8b161e7be808c9d8eaa163d41a..6e2e&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 44)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 44, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 44, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 14:03:10 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'errors' at line 1
Request URL: /Accounts/users/oauth_callback?code=4%2FNtAOawRXd_WaCs32-ad1T2otgNu8Caw1aQAtSx0R1GU.EkYnnV5rXXIbBrG_bnfDxpKUAFLMmQI&authuser=0&num_sessions=2&session_state=07a7b8c639360bfc5d356d4424d11c2dae23fa73..66b0&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('errors', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('errors', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(611): DboSource->fetchAll('errors', Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(827): DboSource->query('errors', Array, Object(User))
#5 C:\xampp\htdocs\Accounts\app\Model\User.php(51): Model->__call('errors', Array)
#6 C:\xampp\htdocs\Accounts\app\Model\User.php(51): User->errors()
#7 C:\xampp\htdocs\Accounts\app\Controller\UsersController.php(208): User->signin(Array)
#8 [internal function]: UsersController->oauth_callback()
#9 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-04-23 14:03:35 Error: Fatal Error (1): Call to a member function errors() on a non-object in [C:\xampp\htdocs\Accounts\app\Model\User.php, line 51]
2015-04-23 14:03:35 Error: [FatalErrorException] Call to a member function errors() on a non-object
Request URL: /Accounts/users/oauth_callback?code=4%2F0RhSkYGZqYtHSrFSQlhe3zitVcNcAZFWT4LadVs5M2Y.4t7xenfLEHkVgrKXntQAax2iw1LMmQI&authuser=0&num_sessions=2&session_state=fe94fe84440f2cce1c8f7d5c65aec2d884d8f85c..e92a&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 51, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 51, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 16:10:15 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 101]
2015-04-23 16:10:15 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/edit/04001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 101)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 101, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 101, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 16:10:34 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 102]
2015-04-23 16:10:34 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/edit/04001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 102)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 102, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 102, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 16:13:39 Error: Fatal Error (4): syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN) in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 103]
2015-04-23 16:13:39 Error: [FatalErrorException] syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN)
Request URL: /Accounts/expenses/edit/04001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 103)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 103, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 103, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 16:19:06 Error: Fatal Error (4): syntax error, unexpected 'var' (T_VAR) in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 11]
2015-04-23 16:19:06 Error: [FatalErrorException] syntax error, unexpected 'var' (T_VAR)
Request URL: /Accounts/expenses/edit/04001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 16:21:28 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 109]
2015-04-23 16:21:28 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /Accounts/expenses/edit/04001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 109)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 109, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 109, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-23 16:24:53 Error: Fatal Error (4): syntax error, unexpected '\' (T_NS_SEPARATOR), expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 11]
2015-04-23 16:24:53 Error: [FatalErrorException] syntax error, unexpected '\' (T_NS_SEPARATOR), expecting ',' or ';'
Request URL: /Accounts/expenses/edit/04001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-24 03:53:21 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 106]
2015-04-24 03:53:21 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /Accounts/expenses/edit/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 106)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 106, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 106, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-27 07:44:45 Error: [MissingViewException] View file "Users\search.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\search.ctp',
)
Request URL: /Accounts/users/search
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-04-28 04:16:19 Error: [MissingViewException] View file "Users\search.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\search.ctp',
)
Request URL: /Accounts/users/search
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-04-28 04:18:12 Error: [MissingViewException] View file "Users\search.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\search.ctp',
)
Request URL: /Accounts/users/search
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-04-28 04:20:36 Error: [MissingViewException] View file "Users\search.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\search.ctp',
)
Request URL: /Accounts/users/search
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-04-28 04:26:46 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\Accounts\app\Controller\UsersController.php, line 45]
2015-04-28 04:26:46 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /Accounts/users/logout
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 45, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 45, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-28 04:32:10 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\View\Users\search.ctp, line 2]
2015-04-28 04:32:10 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/users/search
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-28 04:32:18 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\View\Users\search.ctp, line 2]
2015-04-28 04:32:18 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/users/search
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-28 04:40:17 Error: [MissingActionException] Action UsersController::list() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'list',
)
Request URL: /Accounts/users/list
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-04-28 05:14:40 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Controller\UsersController.php, line 92]
2015-04-28 05:14:40 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 92)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 92, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 92, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-28 06:11:20 Error: Fatal Error (4): syntax error, unexpected 'for' (T_FOR) in [C:\xampp\htdocs\Accounts\app\Controller\UsersController.php, line 89]
2015-04-28 06:11:20 Error: [FatalErrorException] syntax error, unexpected 'for' (T_FOR)
Request URL: /Accounts/users/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 89)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 89, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 89, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-28 06:31:29 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\Controller\UsersController.php, line 101]
2015-04-28 06:31:29 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/users/logout
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 101)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 101, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 101, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-04-28 08:39:51 Error: [MissingViewException] View file "Expenses\admit.ctp" is missing.
Exception Attributes: array (
  'file' => 'Expenses\\admit.ctp',
)
Request URL: /Accounts/expenses/admit/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-05-21 03:14:09 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Accounts\app\View\Users\view.ctp, line 12]
2015-05-21 03:14:09 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /Accounts/users/view/2
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 12, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-21 04:02:06 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 36]
2015-05-21 04:02:06 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /Accounts/expenses/view/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-21 04:02:16 Error: Fatal Error (4): syntax error, unexpected 'echo' (T_ECHO) in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 39]
2015-05-21 04:02:16 Error: [FatalErrorException] syntax error, unexpected 'echo' (T_ECHO)
Request URL: /Accounts/expenses/view/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 39)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 39, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 39, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-21 05:00:35 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 99]
2015-05-21 05:00:35 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/expenses/edit/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-21 05:00:52 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 99]
2015-05-21 05:00:52 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /Accounts/expenses/edit/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 99)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 99, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 99, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-21 05:01:20 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'no' in 'where clause'
Request URL: /Accounts/expenses/edit/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(101): Model->find('first', Array)
#7 [internal function]: ExpensesController->edit('04002')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2015-05-21 11:20:24 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 54]
2015-05-21 11:20:24 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/expenses/view/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 54)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 54, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 54, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-21 11:20:36 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 59]
2015-05-21 11:20:36 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /Accounts/expenses/view/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 59)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 59, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 59, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-22 02:59:31 Error: Fatal Error (4): syntax error, unexpected ''type'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [C:\xampp\htdocs\Accounts\app\View\Users\index.ctp, line 39]
2015-05-22 02:59:31 Error: [FatalErrorException] syntax error, unexpected ''type'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /Accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 39)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 39, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 39, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-22 03:03:38 Error: [MissingViewException] View file "Expenses\book.ctp" is missing.
Exception Attributes: array (
  'file' => 'Expenses\\book.ctp',
)
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-05-22 03:11:13 Error: Fatal Error (4): syntax error, unexpected '*' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 235]
2015-05-22 03:11:13 Error: [FatalErrorException] syntax error, unexpected '*'
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 235)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 235, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 235, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-22 03:40:54 Error: Fatal Error (4): syntax error, unexpected ':', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\book.ctp, line 8]
2015-05-22 03:40:54 Error: [FatalErrorException] syntax error, unexpected ':', expecting ',' or ';'
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-22 03:45:25 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 108]
2015-05-22 03:45:25 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=5
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 108)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 108, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 108, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-22 12:37:59 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'price' cannot be null
Request URL: /Accounts/expenses/edit/05002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(Expense), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(154): Model->save(Array)
#6 [internal function]: ExpensesController->edit('05002')
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-05-29 07:21:20 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\Accounts\lib\Cake\View\Helper\FormHelper.php, line 1675]
2015-05-29 07:21:20 Error: [FatalErrorException] Unsupported operand types
Request URL: /Accounts/expenses/view/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\xampp\htdocs...', 1675)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\xampp\htdocs...', 1675, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\xampp\htdocs...', 1675, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-29 07:21:48 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\Accounts\lib\Cake\View\Helper\FormHelper.php, line 1675]
2015-05-29 07:21:48 Error: [FatalErrorException] Unsupported operand types
Request URL: /Accounts/expenses/view/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\xampp\htdocs...', 1675)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\xampp\htdocs...', 1675, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\xampp\htdocs...', 1675, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-05-29 07:27:07 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 7]
2015-05-29 07:27:07 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /Accounts/expenses/view/04002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 7, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 7, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-08 04:39:04 Error: Fatal Error (64): Cannot redeclare class Expense in [C:\xampp\htdocs\Accounts\app\Model\Dept.php, line 5]
2015-06-08 04:39:04 Error: [FatalErrorException] Cannot redeclare class Expense
Request URL: /Accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 5, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 5, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-08 04:41:08 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'team' in 'where clause'
Request URL: /Accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\UsersController.php(41): Model->find('all', Array)
#7 [internal function]: UsersController->index('home')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2015-06-08 04:43:55 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'team' in 'where clause'
Request URL: /Accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\UsersController.php(41): Model->find('all', Array)
#7 [internal function]: UsersController->index('home')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2015-06-08 04:48:09 Error: [MissingControllerException] Controller class DeptController could not be found.
Exception Attributes: array (
  'class' => 'DeptController',
  'plugin' => NULL,
)
Request URL: /Accounts/dept/search
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-06-08 04:50:08 Error: Fatal Error (1): Call to undefined method DeptsController::redirct() in [C:\xampp\htdocs\Accounts\app\Controller\DeptsController.php, line 28]
2015-06-08 04:50:08 Error: [FatalErrorException] Call to undefined method DeptsController::redirct()
Request URL: /Accounts/depts/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 28)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 28, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 28, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-08 05:00:41 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\Controller\BigsController.php, line 33]
2015-06-08 05:00:41 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/bigs/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 33, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 33, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-08 05:00:56 Error: [MissingControllerException] Controller class BigsController could not be found.
Exception Attributes: array (
  'class' => 'BigsController',
  'plugin' => NULL,
)
Request URL: /Accounts/bigs/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-06-08 05:28:11 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Dept.dept_id' in 'field list'
Request URL: /Accounts/smalls/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Dept`.`...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Dept`.`...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Dept`.`...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Dept), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(34): Model->find('list', Array)
#7 [internal function]: SmallsController->add()
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2015-06-08 14:35:00 Error: Fatal Error (4): syntax error, unexpected 'var' (T_VAR) in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 26]
2015-06-08 14:35:00 Error: [FatalErrorException] syntax error, unexpected 'var' (T_VAR)
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 26, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 26, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-08 15:54:18 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 61]
2015-06-08 15:54:18 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/expenses/view/06001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 61)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 61, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 61, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-08 16:52:06 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 185]
2015-06-08 16:52:06 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /Accounts/expenses/edit/06001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 185)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 185, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 185, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-10 09:35:27 Error: [MissingControllerException] Controller class AccountsController could not be found.
Exception Attributes: array (
  'class' => 'AccountsController',
  'plugin' => NULL,
)
Request URL: /Accounts/accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-06-10 09:35:54 Error: [MissingViewException] View file "Expenses\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'Expenses\\add.ctp',
)
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-06-10 16:57:17 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php, line 39]
2015-06-10 16:57:17 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /Accounts/smalls/view
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 39)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 39, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 39, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-10 17:41:20 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php, line 61]
2015-06-10 17:41:20 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/smalls/view
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 61)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 61, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 61, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-06-14 10:35:19 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/edit/06001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(Expense), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(199): Model->save(Array)
#6 [internal function]: ExpensesController->edit('06001')
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-06-14 10:38:03 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF) in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 149]
2015-06-14 10:38:03 Error: [FatalErrorException] syntax error, unexpected 'if' (T_IF)
Request URL: /Accounts/expenses/view/06002
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 149)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 149, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 149, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-12 17:11:34 Error: [MissingControllerException] Controller class AccountsController could not be found.
Exception Attributes: array (
  'class' => 'AccountsController',
  'plugin' => NULL,
)
Request URL: /Accounts/accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-07-12 17:11:51 Error: Fatal Error (4): syntax error, unexpected '=', expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\Expense.php, line 7]
2015-07-12 17:11:51 Error: [FatalErrorException] syntax error, unexpected '=', expecting ')'
Request URL: /Accounts/users/oauth_callback?code=4%2F8wBBxr8Hy5tLCWWzFBWvfQZFrR7nZ3ENosebbpIWo1Y&authuser=3&hd=wasedasai.net&session_state=23b17da45610ed1a9faf2817cc97b54b26890002..b2e2&prompt=none
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 7, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 7, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-12 17:18:52 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(Expense), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(55): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-07-12 18:00:22 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(Expense), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(55): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-07-12 18:00:54 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(AppModel), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(55): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-07-12 18:03:08 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(AppModel), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(55): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-07-12 18:03:23 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(AppModel), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(55): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-07-12 18:03:38 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(AppModel), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(55): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-07-12 18:04:53 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'small_id' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(AppModel), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(55): Model->save(Array)
#6 [internal function]: ExpensesController->add()
#7 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#8 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2015-07-19 09:10:06 Error: [MissingControllerException] Controller class AccountsController could not be found.
Exception Attributes: array (
  'class' => 'AccountsController',
  'plugin' => NULL,
)
Request URL: /Accounts/accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-07-19 09:34:07 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 8]
Trace:
include - APP\View\Expenses\add.ctp, line 8
View::_evaluate() - CORE\Cake\View\View.php, line 962
View::_render() - CORE\Cake\View\View.php, line 924
View::render() - CORE\Cake\View\View.php, line 473
Controller::render() - CORE\Cake\Controller\Controller.php, line 960
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 200
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 167
[main] - APP\webroot\index.php, line 118

2015-07-19 09:34:07 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\Accounts\app\View\Expenses\add.ctp, line 14]
Trace:
include - APP\View\Expenses\add.ctp, line 14
View::_evaluate() - CORE\Cake\View\View.php, line 962
View::_render() - CORE\Cake\View\View.php, line 924
View::render() - CORE\Cake\View\View.php, line 473
Controller::render() - CORE\Cake\Controller\Controller.php, line 960
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 200
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 167
[main] - APP\webroot\index.php, line 118

2015-07-19 09:54:13 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\Accounts\app\View\Expenses\book.ctp, line 36]
2015-07-19 09:54:13 Error: [InternalErrorException] Internal Server Error
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=7
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-19 09:55:11 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\Accounts\app\View\Expenses\book.ctp, line 36]
2015-07-19 09:55:11 Error: [FatalErrorException] syntax error, unexpected '='
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=7
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 36, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-19 16:41:49 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\View\Expenses\book.ctp, line 6]
2015-07-19 16:41:49 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=6
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 6)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 6, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 6, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 07:27:37 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 371]
2015-07-29 07:27:37 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=6
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 07:29:40 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 371]
2015-07-29 07:29:40 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=6
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 07:29:43 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 371]
2015-07-29 07:29:43 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=6
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 07:29:44 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 371]
2015-07-29 07:29:44 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/expenses/book?month%5Bmonth%5D=6
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 371, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 09:44:10 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 60]
2015-07-29 09:44:10 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /Accounts/expenses/edit/06005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 60)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 60, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 60, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 09:44:25 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 60]
2015-07-29 09:44:25 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/expenses/edit/06005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 60)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 60, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 60, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 09:44:44 Error: Fatal Error (1): Call to undefined function ms_substr() in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 60]
2015-07-29 09:44:44 Error: [FatalErrorException] Call to undefined function ms_substr()
Request URL: /Accounts/expenses/edit/06005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 60)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 60, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 60, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 09:51:17 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 16]
2015-07-29 09:51:17 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /Accounts/expenses/view/06005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 16)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 16, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 16, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 09:51:42 Error: Fatal Error (4): syntax error, unexpected '!', expecting variable (T_VARIABLE) or '$' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 47]
2015-07-29 09:51:42 Error: [FatalErrorException] syntax error, unexpected '!', expecting variable (T_VARIABLE) or '$'
Request URL: /Accounts/expenses/view/06005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-07-29 12:46:47 Error: Fatal Error (4): syntax error, unexpected ''.$this->Html->link('' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Users\index.ctp, line 25]
2015-07-29 12:46:47 Error: [FatalErrorException] syntax error, unexpected ''.$this->Html->link('' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';'
Request URL: /Accounts/users
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 25, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 25, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-04 08:59:13 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE), expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 116]
2015-08-04 08:59:14 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE), expecting ',' or ';'
Request URL: /Accounts/expenses/view/06001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 116)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 116, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 116, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-04 11:16:06 Error: Fatal Error (4): syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 180]
2015-09-04 11:16:06 Error: [FatalErrorException] syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$'
Request URL: /Accounts/expenses/edit/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 180)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 180, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 180, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-04 11:18:45 Error: Fatal Error (4): syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 180]
2015-09-04 11:18:45 Error: [FatalErrorException] syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$'
Request URL: /Accounts/expenses/edit/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 180)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 180, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 180, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-04 11:20:10 Error: Fatal Error (4): syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 180]
2015-09-04 11:20:10 Error: [FatalErrorException] syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$'
Request URL: /Accounts/expenses/edit/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 180)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 180, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 180, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 12:10:25 Error: Fatal Error (4): syntax error, unexpected '"';\n"' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\edit.ctp, line 130]
2015-09-06 12:10:25 Error: [FatalErrorException] syntax error, unexpected '"';\n"' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';'
Request URL: /Accounts/expenses/edit/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 130)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 130, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 130, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 12:28:57 Error: Fatal Error (1): Call to undefined function emReplace() in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 235]
2015-09-06 12:28:57 Error: [FatalErrorException] Call to undefined function emReplace()
Request URL: /Accounts/expenses/edit/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 235)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 235, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 235, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 12:29:35 Error: Fatal Error (1): Call to undefined function emReplace() in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 235]
2015-09-06 12:29:35 Error: [FatalErrorException] Call to undefined function emReplace()
Request URL: /Accounts/expenses/edit/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 235)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 235, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 235, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 12:30:22 Error: Fatal Error (1): Call to undefined function emReplace() in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 242]
2015-09-06 12:30:22 Error: [FatalErrorException] Call to undefined function emReplace()
Request URL: /Accounts/expenses/edit/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 242)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 242, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 242, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 13:03:07 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 69]
2015-09-06 13:03:07 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /Accounts/expenses/view/090012
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 69)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 69, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 69, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 14:59:41 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\detailedit.ctp, line 45]
2015-09-06 14:59:41 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /Accounts/expenses/detailedit/23
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 45, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 45, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 15:00:04 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\detailedit.ctp, line 46]
2015-09-06 15:00:04 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /Accounts/expenses/detailedit/23
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 46)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 46, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 46, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 15:03:35 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 307]
2015-09-06 15:03:35 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/expenses/detailedit/23
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 307)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 307, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 307, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-06 16:50:13 Error: [MissingViewException] View file "Expenses\all_reported.ctp" is missing.
Exception Attributes: array (
  'file' => 'Expenses\\all_reported.ctp',
)
Request URL: /Accounts/expenses/allReported/6
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-09-06 18:51:22 Error: Fatal Error (4): syntax error, unexpected 'foreach' (T_FOREACH), expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Users\refund.ctp, line 35]
2015-09-06 18:51:22 Error: [FatalErrorException] syntax error, unexpected 'foreach' (T_FOREACH), expecting ',' or ';'
Request URL: /Accounts/users/refund/1
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 35)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 35, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 35, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-09-07 08:38:10 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\View\Users\refund.ctp, line 2]
2015-09-07 08:38:10 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/users/refund
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:07:49 Error: [MissingActionException] Action SmallsController::budget() could not be found.
Exception Attributes: array (
  'controller' => 'SmallsController',
  'action' => 'budget',
)
Request URL: /Accounts/smalls/budget
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-10-11 08:09:31 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\View\Smalls\budget.ctp, line 14]
2015-10-11 08:09:31 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/smalls/budget
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:21:40 Error: Fatal Error (4): syntax error, unexpected '$small' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\View\Smalls\budget.ctp, line 13]
2015-10-11 08:21:40 Error: [FatalErrorException] syntax error, unexpected '$small' (T_VARIABLE)
Request URL: /Accounts/smalls/budget
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:22:31 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\View\Smalls\budget.ctp, line 13]
2015-10-11 08:22:31 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/smalls/budget
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 13, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 13, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:29:46 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php, line 60]
2015-10-11 08:29:46 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/smalls/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 60)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 60, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 60, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:30:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php, line 60]
2015-10-11 08:30:12 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /Accounts/smalls/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 60)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 60, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 60, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:37:47 Error: Fatal Error (4): syntax error, unexpected '$sum' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\View\Smalls\check.ctp, line 22]
2015-10-11 08:37:47 Error: [FatalErrorException] syntax error, unexpected '$sum' (T_VARIABLE)
Request URL: /Accounts/smalls/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 22)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 22, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 22, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:38:31 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\View\Smalls\check.ctp, line 22]
2015-10-11 08:38:31 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/smalls/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 22)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 22, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 22, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:38:51 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\View\Smalls\check.ctp, line 22]
2015-10-11 08:38:51 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/smalls/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 22)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 22, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 22, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 08:39:53 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\View\Smalls\check.ctp, line 9]
2015-10-11 08:39:53 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/smalls/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 9, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 9, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 14:39:50 Error: Fatal Error (4): syntax error, unexpected 'echo' (T_ECHO), expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Users\index.ctp, line 131]
2015-10-11 14:39:50 Error: [FatalErrorException] syntax error, unexpected 'echo' (T_ECHO), expecting ',' or ';'
Request URL: /Accounts/users
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 131)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 131, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 131, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-11 14:40:08 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\Accounts\app\View\Users\index.ctp, line 133]
2015-10-11 14:40:08 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /Accounts/users
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 133)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 133, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 133, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-15 08:16:30 Error: Fatal Error (4): syntax error, unexpected ',', expecting ')' in [C:\xampp\htdocs\Accounts\app\Controller\UsersController.php, line 105]
2015-10-15 08:16:30 Error: [FatalErrorException] syntax error, unexpected ',', expecting ')'
Request URL: /Accounts/users/refund
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 105)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 105, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 105, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-10-15 08:27:16 Error: [MissingActionException] Action UsersController::setRefunded() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'setRefunded',
)
Request URL: /Accounts/users/setRefunded/5
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-11-11 05:15:01 Error: [MissingControllerException] Controller class ItemsController could not be found.
Exception Attributes: array (
  'class' => 'ItemsController',
  'plugin' => NULL,
)
Request URL: /Accounts/items/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-11-11 08:28:13 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [C:\xampp\htdocs\Accounts\app\Model\Small.php, line 5]
2015-11-11 08:28:13 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /Accounts/items/view
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 5, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 5, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-11-11 08:28:45 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\Accounts\app\View\Items\view.ctp, line 17]
2015-11-11 08:28:45 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /Accounts/items/view
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 17, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-11-11 08:38:14 Error: Fatal Error (4): syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$' in [C:\xampp\htdocs\Accounts\app\View\Items\edit.ctp, line 14]
2015-11-11 08:38:14 Error: [FatalErrorException] syntax error, unexpected '(', expecting variable (T_VARIABLE) or '$'
Request URL: /Accounts/items/edit/2
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 14, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 14, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-11-11 09:42:03 Error: Fatal Error (4): syntax error, unexpected '>' in [C:\xampp\htdocs\Accounts\app\View\Items\check.ctp, line 34]
2015-11-11 09:42:03 Error: [FatalErrorException] syntax error, unexpected '>'
Request URL: /Accounts/items/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 34, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 34, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-12-10 15:31:09 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 90]
2015-12-10 15:31:09 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /Accounts/expenses/view/06003
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 90)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 90, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 90, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-12-10 16:40:40 Error: Fatal Error (1): Call to a member function addRow() on a non-object in [C:\xampp\htdocs\Accounts\app\View\Expenses\download.ctp, line 3]
2015-12-10 16:40:40 Error: [FatalErrorException] Call to a member function addRow() on a non-object
Request URL: /Accounts/expenses/download/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-12-10 16:41:49 Error: Fatal Error (1): Call to a member function addRow() on a non-object in [C:\xampp\htdocs\Accounts\app\View\Expenses\download.ctp, line 3]
2015-12-10 16:41:49 Error: [FatalErrorException] Call to a member function addRow() on a non-object
Request URL: /Accounts/expenses/download/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-12-14 03:53:26 Error: Fatal Error (1): Function name must be a string in [C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php, line 107]
2015-12-14 03:53:26 Error: [FatalErrorException] Function name must be a string
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Function name m...', 'C:\xampp\htdocs...', 107)
#1 [internal function]: ErrorHandler::handleError(1, 'Function name m...', 'C:\xampp\htdocs...', 107, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Function name m...', 'C:\xampp\htdocs...', 107, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-01-08 09:13:44 Error: [MissingViewException] View file "Expenses\view_all_datas.ctp" is missing.
Exception Attributes: array (
  'file' => 'Expenses\\view_all_datas.ctp',
)
Request URL: /Accounts/expenses/viewAllDatas
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-01-13 03:26:39 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'small_id' in where clause is ambiguous
Request URL: /Accounts/expenses/view/07005
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(146): Model->find('first', Array)
#7 [internal function]: ExpensesController->view('07005')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-19 08:39:27 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'no' cannot be null
Request URL: /Accounts/expenses/add
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ac...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ac...')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1928): DboSource->create(Object(Expense), Array, Array)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1745): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2338): Model->save(Array, Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(90): Model->saveMany(Array)
#7 C:\xampp\htdocs\Accounts\app\Controller\ExpensesController.php(105): ExpensesController->saveAllDatas(Array)
#8 [internal function]: ExpensesController->add()
#9 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ExpensesController), Array)
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ExpensesController), Object(CakeRequest))
#12 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2016-01-24 11:57:43 Error: Fatal Error (4): syntax error, unexpected '[' in [C:\xampp\htdocs\Accounts\app\View\Items\check.ctp, line 52]
2016-01-24 11:57:43 Error: [FatalErrorException] syntax error, unexpected '['
Request URL: /Accounts/items/check
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 52, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-01-24 11:57:54 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /Accounts/user
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-01-24 11:58:00 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /Accounts/user
Stack Trace:
#0 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-01-24 12:20:13 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\Accounts\app\View\Items\itemlist.ctp, line 9]
2016-01-24 12:20:13 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /Accounts/items/itemlist/1
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 9, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 9, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-01-24 12:33:53 Error: [MissingActionException] Action ItemsController::smalllist() could not be found.
Exception Attributes: array (
  'controller' => 'ItemsController',
  'action' => 'smalllist',
)
Request URL: /Accounts/items/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ItemsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-01-24 12:34:29 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'small_id' in where clause is ambiguous
Request URL: /Accounts/smalls/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(72): Model->find('all', Array)
#7 [internal function]: SmallsController->smalllist('14')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-24 12:35:38 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'small_id' in where clause is ambiguous
Request URL: /Accounts/smalls/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(72): Model->find('all', Array)
#7 [internal function]: SmallsController->smalllist('14')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-24 12:36:28 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Expensesmall_id' in 'where clause'
Request URL: /Accounts/smalls/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(72): Model->find('all', Array)
#7 [internal function]: SmallsController->smalllist('14')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-24 12:36:52 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.'small_id' = '14'' at line 1
Request URL: /Accounts/smalls/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(72): Model->find('all', Array)
#7 [internal function]: SmallsController->smalllist('14')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-24 12:37:04 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'small_id' in where clause is ambiguous
Request URL: /Accounts/smalls/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(72): Model->find('all', Array)
#7 [internal function]: SmallsController->smalllist('14')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-24 12:38:47 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'small_id`` = 14' at line 1
Request URL: /Accounts/smalls/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(72): Model->find('all', Array)
#7 [internal function]: SmallsController->smalllist('14')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-24 12:44:31 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
Request URL: /Accounts/smalls/smalllist/14
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Small`....', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Small`....', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Small`....', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Small), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\SmallsController.php(71): Model->find('first', Array)
#7 [internal function]: SmallsController->smalllist('14')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SmallsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(SmallsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-24 12:48:33 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
Request URL: /Accounts/items/itemlist/1
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Item`.`...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Item`.`...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Item`.`...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Item), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\ItemsController.php(61): Model->find('first', Array)
#7 [internal function]: ItemsController->itemlist('1')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ItemsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ItemsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-27 12:04:04 Error: Fatal Error (4): syntax error, unexpected '>' in [C:\xampp\htdocs\Accounts\app\View\Expenses\view.ctp, line 238]
2016-01-27 12:04:04 Error: [FatalErrorException] syntax error, unexpected '>'
Request URL: /Accounts/expenses/view/06001
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 238)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 238, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 238, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-03 05:16:27 Error: [MissingViewException] View file "Users\refundlist.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\refundlist.ctp',
)
Request URL: /Accounts/users/refundlist
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-02-03 05:46:52 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\Accounts\app\Controller\UsersController.php, line 150]
2016-02-03 05:46:52 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /Accounts/users/refundlist
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 150)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 150, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 150, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-12 05:20:24 Error: [MissingActionException] Action ItemsController::closing() could not be found.
Exception Attributes: array (
  'controller' => 'ItemsController',
  'action' => 'closing',
)
Request URL: /Accounts/items/closing
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(ItemsController), Object(CakeRequest))
#2 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-02-12 06:28:15 Error: Fatal Error (4): syntax error, unexpected '$expenses' (T_VARIABLE), expecting ')' in [C:\xampp\htdocs\Accounts\app\Controller\ItemsController.php, line 144]
2016-02-12 06:28:15 Error: [FatalErrorException] syntax error, unexpected '$expenses' (T_VARIABLE), expecting ')'
Request URL: /Accounts/items/closing
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 144)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 144, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 144, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-14 05:49:32 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
Request URL: /Accounts/bigs/closing/1
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Big`.`i...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Big`.`i...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Big`.`i...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Big), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\BigsController.php(96): Model->find('all', Array)
#7 [internal function]: BigsController->closing('1')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(BigsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(BigsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-02-14 05:50:06 Error: [MissingViewException] View file "Bigs\closing.ctp" is missing.
Exception Attributes: array (
  'file' => 'Bigs\\closing.ctp',
)
Request URL: /Accounts/bigs/closing/1
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(BigsController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-02-14 05:54:38 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\BigsController.php, line 96]
2016-02-14 05:54:38 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /Accounts/bigs/closing/3
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 96)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 96, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 96, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-14 05:54:59 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'big_id' in where clause is ambiguous
Request URL: /Accounts/bigs/closing/3
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Expense...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Expense...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Expense...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Expense), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\BigsController.php(96): Model->find('all', Array)
#7 [internal function]: BigsController->closing('3')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(BigsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(BigsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-02-14 06:10:41 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\Accounts\app\Controller\BigsController.php, line 144]
2016-02-14 06:10:41 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /Accounts/bigs/closing/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 144)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 144, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 144, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-14 06:16:55 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\BigsController.php, line 98]
2016-02-14 06:16:55 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /Accounts/bigs/closing/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 98)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 98, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 98, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-14 06:18:31 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Big.big_id' in 'where clause'
Request URL: /Accounts/bigs/closing/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Big`.`i...', Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Big`.`i...', Array, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Big`.`i...', false)
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Big), Array)
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(2994): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\Accounts\app\Controller\BigsController.php(98): Model->find('first', Array)
#7 [internal function]: BigsController->closing('4')
#8 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(BigsController), Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(BigsController), Object(CakeRequest))
#11 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-02-14 06:23:24 Error: Fatal Error (1): Call to a member function unbindModel() on a non-object in [C:\xampp\htdocs\Accounts\app\Controller\BigsController.php, line 101]
2016-02-14 06:23:24 Error: [FatalErrorException] Call to a member function unbindModel() on a non-object
Request URL: /Accounts/bigs/closing/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 101)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 101, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 101, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-14 06:29:46 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF) in [C:\xampp\htdocs\Accounts\app\Controller\BigsController.php, line 155]
2016-02-14 06:29:46 Error: [FatalErrorException] syntax error, unexpected 'if' (T_IF)
Request URL: /Accounts/bigs/closing/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 155)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 155, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 155, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-14 06:41:29 Error: Fatal Error (4): syntax error, unexpected ',', expecting ')' in [C:\xampp\htdocs\Accounts\app\Controller\BigsController.php, line 191]
2016-02-14 06:41:29 Error: [FatalErrorException] syntax error, unexpected ',', expecting ')'
Request URL: /Accounts/bigs/closing/4
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 191)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 191, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 191, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 15:42:15 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 71]
2016-03-19 15:42:15 Error: [FatalErrorException] syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION)
Request URL: /Accounts/
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 71)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 71, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 71, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:01:40 Error: Fatal Error (4): syntax error, unexpected '$', expecting variable (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 82]
2016-03-19 16:01:40 Error: [FatalErrorException] syntax error, unexpected '$', expecting variable (T_VARIABLE)
Request URL: /Accounts/users
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 82)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 82, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 82, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:31:36 Error: [MissingActionException] Action UsersController::changeYear() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'changeYear',
)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-03-19 16:32:00 Error: [MissingViewException] View file "Users\change_year.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\change_year.ctp',
)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-19 16:32:02 Error: [MissingViewException] View file "Users\change_year.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\change_year.ctp',
)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-19 16:32:02 Error: [MissingViewException] View file "Users\change_year.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\change_year.ctp',
)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-03-19 16:48:12 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 97]
2016-03-19 16:48:12 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 97)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 97, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 97, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:49:03 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 98]
2016-03-19 16:49:03 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 98)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 98, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 98, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:49:05 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 98]
2016-03-19 16:49:05 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 98)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 98, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 98, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:49:26 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 99]
2016-03-19 16:49:26 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:49:31 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 99]
2016-03-19 16:49:31 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:53:26 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 99]
2016-03-19 16:53:26 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 99, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:53:45 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 98]
2016-03-19 16:53:45 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 98)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 98, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 98, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:53:56 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [C:\xampp\htdocs\Accounts\app\Config\database.php, line 103]
2016-03-19 16:53:56 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 103)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 103, Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 103, Array)
#3 C:\xampp\htdocs\Accounts\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-03-19 16:54:12 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1049] Unknown database \'accounts2016\'',
  'enabled' => true,
)
Request URL: /Accounts/users/changeYear
Stack Trace:
#0 C:\xampp\htdocs\Accounts\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\xampp\htdocs\Accounts\lib\Cake\Model\ConnectionManager.php(105): DboSource->__construct(Array)
#2 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3617): ConnectionManager::getDataSource('default')
#3 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1155): Model->setDataSource('default')
#4 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(3644): Model->setSource('users')
#5 C:\xampp\htdocs\Accounts\lib\Cake\Model\Model.php(1387): Model->getDataSource()
#6 C:\xampp\htdocs\Accounts\lib\Cake\View\Helper\FormHelper.php(215): Model->schema()
#7 C:\xampp\htdocs\Accounts\lib\Cake\View\Helper\FormHelper.php(468): FormHelper->_introspectModel('User', 'fields')
#8 C:\xampp\htdocs\Accounts\app\View\Users\change_year.ctp(3): FormHelper->create('User', Array)
#9 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(962): include('C:\xampp\htdocs...')
#10 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(924): View->_evaluate('C:\xampp\htdocs...', Array)
#11 C:\xampp\htdocs\Accounts\lib\Cake\View\View.php(473): View->_render('C:\xampp\htdocs...')
#12 C:\xampp\htdocs\Accounts\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#13 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#14 C:\xampp\htdocs\Accounts\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 C:\xampp\htdocs\Accounts\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
